### ISSUE TITLE
Feature 1: Host can add a pool

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Host can add a pool.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Host can fill out a form to add a pool

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-26 at 12 15 07 PM](https://user-images.githubusercontent.com/78885956/119720344-b468de80-be1e-11eb-95e3-1350266e238e.png)
![Screen Shot 2021-05-26 at 12 33 38 PM](https://user-images.githubusercontent.com/78885956/119720350-b632a200-be1e-11eb-8c61-6a565e12fa3c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a "hosts" table and a "pools" table
- [x] Update `data.sql` to add hostId, name, poolId. and poolId, location, price, description, rules, amenities, img, hostId

### ☁️ Server

- [x] Update `server/index.js` to have a post method  
- [x] query database to add hosts info
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a header component 
- [x] Create a form component for adding a pool
- [x] add css for form
- [x] Update component to send a POST fetch request onSubmit

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
