### ISSUE TITLE
Feature: User can sign up as a host or swimmer.

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up as a host or swimmer

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can click sign up to create an account

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-03 at 4 11 16 PM](https://user-images.githubusercontent.com/78885956/120724759-50cb5a80-c489-11eb-9b0d-ef8fdb5d1790.png)
![Screen Shot 2021-06-03 at 4 32 02 PM](https://user-images.githubusercontent.com/78885956/120724761-5163f100-c489-11eb-8a27-302fd9435380.png)
![Screen Shot 2021-06-03 at 4 10 58 PM](https://user-images.githubusercontent.com/78885956/120724785-5d4fb300-c489-11eb-9fbe-85c53866a0cd.png)
![Screen Shot 2021-06-03 at 4 34 52 PM](https://user-images.githubusercontent.com/78885956/120724930-a869c600-c489-11eb-87a8-a5b4d9f33f54.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have "hosts" and "swimmers" tables include username and password

### ☁️ Server

- [x] install argon2 
- [x] Update swimmer and host post route to take in username and password, hash pw, and add to db query
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a sign up form component
- [x] add sign up button onSubmit event.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
