### ISSUE TITLE
Feature 2: Swimmer can search for pools by location

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Swimmer can search for pools by location

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Swimmers can search for pools by location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-26 at 4 53 59 PM](https://user-images.githubusercontent.com/78885956/119745492-14717c00-be43-11eb-9af2-8034fbb18b7f.png)
![Screen Shot 2021-05-26 at 4 54 16 PM](https://user-images.githubusercontent.com/78885956/119745494-150a1280-be43-11eb-9f19-037f5d3a54de.png)

![Screen Shot 2021-05-26 at 1 31 26 PM](https://user-images.githubusercontent.com/78885956/119727089-c0f13500-be26-11eb-80a7-6dfddedea537.png)
![Screen Shot 2021-05-26 at 1 31 43 PM](https://user-images.githubusercontent.com/78885956/119727093-c2226200-be26-11eb-9b5e-f7f44c146fe3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a get method
- [x] query the database to get "pools" with requested location
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to let user choose host or swimmer
- [x] Create an input component to search by location
- [x] create navbar component and add search to go to search view
- [x] Update search component to have an onSubmit prop  to send a fetch GET request
- [x] add component to render list of pools for location
- [x] add css for pool list component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
