### ISSUE TITLE
Feature: Swimmer can view the details of a pool

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Swimmer can view the details of a pool

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Swimmer can click on a pool to view the information on that pool.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-28 at 11 47 30 AM](https://user-images.githubusercontent.com/78885956/120029193-9a5c0700-bfaa-11eb-8c21-99d32b96f234.png)

![Screen Shot 2021-05-28 at 12 35 28 PM](https://user-images.githubusercontent.com/78885956/120033979-3983fd00-bfb1-11eb-96f5-31769807c119.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a get request for a single pool
- [x] query the database to select pool by poolId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update pool list to have an each pool wrapped in an a element
- [x] Create a component to render pool information view
- [x] add css for pool information view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
