### ISSUE TITLE
Feature: Host can view their pools information.

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Host can view their pools information

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Host can click on one of their pools to view its information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update host pool list component to have each pool wrapped in an a element to change view to pool info.
- [x] Create a component to render pool information for host using existing get route.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
