### ISSUE TITLE
Feature: Host can edit a pools information

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#34]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Host can edit a pools information 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Host can click on an edit button to edit one of their pools information

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a put route for editing a pool by poolId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update host pool information component to have an edit button
- [x] Create a component to render pool form pre-populated with the pools information
- [x] Add event listener for submit and cancel
- [x] css

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
