### ISSUE TITLE
Feature: Swimmer can send a booking request to a host

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Swimmer can send a booking request to a host.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Swimmer can click book now on a pool and select a date and time to send a booking request to a host

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-28 at 2 39 58 PM](https://user-images.githubusercontent.com/78885956/120045986-0a2bbb00-bfc6-11eb-9bb4-3e9d4cbfd8bd.png)
![Screen Shot 2021-05-28 at 2 48 03 PM](https://user-images.githubusercontent.com/78885956/120045987-0ac45180-bfc6-11eb-8da3-13bef776b8d3.png)
![Screen Shot 2021-05-31 at 9 23 41 PM](https://user-images.githubusercontent.com/78885956/120266430-bb488480-c256-11eb-84c8-0bf81b9a3c89.png)
![Screen Shot 2021-05-31 at 9 25 04 PM](https://user-images.githubusercontent.com/78885956/120266433-bc79b180-c256-11eb-8e7b-e860cf5a44c9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a "bookingRequests" table with "swimmerId", "poolId", "date", "time", "status" and "bookingId" attributes
- [x] Update `schema.sql to have a "swimmers" table

### ☁️ Server

- [x] Update `server/index.js` to have a post method
- [x] query the database to insert a booking request into the "bookingRequests" table.
- [x] Update `server/index.js` to have a post method to create a swimmer.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update pool info component to have a book now button
- [x] Create component for entering name when swimmer button is clicked on homepage
- [x] Create a modal form component
- [x] Update book now button to render modal form onClick
- [x] Update modal to send fetch post request to add a booking onSubmit
- [x] css

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
