### ISSUE TITLE
Feature 5: Host can view a list of pending booking requests

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Host can view a list of pending booking requests.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Host can click on booking requests icon to view all of their pending booking requests.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-02 at 11 17 13 AM](https://user-images.githubusercontent.com/78885956/120532082-2ba8f000-c394-11eb-8273-ff16ac8a1ce3.png)
![Screen Shot 2021-06-02 at 11 17 34 AM](https://user-images.githubusercontent.com/78885956/120532084-2c418680-c394-11eb-94dd-2a184e4a02e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a get route to get pending booking requests for a host
- [x] Update `server/index.js to have a post route to add a host to the "hosts" table in the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render pending booking requests
- [x] Create a navbar component for host
- [x] Add booking request icon to navbar
- [x] add css

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
