### ISSUE TITLE
Feature: Host can accept or decline a booking request

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/Oasis#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Host can accept to decline a booking request

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Host  can click a button to either accept or decline a booking request

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-06-02 at 3 39 22 PM](https://user-images.githubusercontent.com/78885956/120561250-07abd580-c3b9-11eb-88f3-52841386d44e.png)
![Screen Shot 2021-06-02 at 3 41 17 PM](https://user-images.githubusercontent.com/78885956/120561251-08446c00-c3b9-11eb-8f02-54095b34b357.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a put route to update a "bookingRequest" "status"
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update booking requests component to have accept and decline buttons for each booking request
- [x] add onClick event to buttons to send a put fetch request.
- [x] add css

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
